### ISSUE TITLE
Can't cross-compile from x86_64 to armv6 (Raspberry Pi)

### ISSUE THREAD

**Issue by piranna** [nodejs/node-v0.x-archive#9073]
I'm using a cross-compiler based on Cross Linux From Scratch to compile Node.js for NodeOS. The cross-compiler works correctly for i686 & x86_64, but when compiling for armv6 I'm always getting the next error:

```
  armv6-nodeos-linux-musleabihf-g++ '-DOPENSSL_NO_SSL2=1' '-DV8_TARGET_ARCH_ARM' '-DENABLE_DISASSEMBLER' '-DV8_USE_DEFAULT_PLATFORM' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DENABLE_HANDLE_ZAPPING' -I../deps/v8/src  -pthread -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -marm -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -MMD -MF /home/piranna/Proyectos/NodeOS/node_modules/nodeos-barebones/deps/node/out/Release/.deps//home/piranna/Proyectos/NodeOS/node_modules/nodeos-barebones/deps/node/out/Release/obj.target/v8_base.arm/deps/v8/src/arm/disasm-arm.o.d.raw -nostdinc -nostdinc++ -c -o /home/piranna/Proyectos/NodeOS/node_modules/nodeos-barebones/deps/node/out/Release/obj.target/v8_base.arm/deps/v8/src/arm/disasm-arm.o ../deps/v8/src/arm/disasm-arm.cc
../deps/v8/src/arm/cpu-arm.cc: In static member function 'static void v8::internal::CPU::FlushICache(void*, size_t)':
../deps/v8/src/arm/cpu-arm.cc:54:40: error: '__ARM_NR_cacheflush' was not declared in this scope
```

`__ARM_NR_cacheflush` is defined in the Linux kernel headers at `asm/unistd.h`.I've been diging on the Node.js code and that file is included at `cpu.cc` as

``` c++
#include "cpu.h"

#if V8_LIBC_MSVCRT
#include <intrin.h>  // __cpuid()
#endif
#if V8_OS_POSIX
#include <unistd.h>  // sysconf()
#endif
#if V8_OS_QNX
#include <sys/syspage.h>  // cpuinfo
#endif
```

I think that block maybe should be included at `cpu.h` so `__ARM_NR_cacheflush` could be defined for `cpu-arm.cc`. The only strange thing about this is about the usage of `<unistd.h>` in the include instead of `<asm/unistd.h>` or similar, since there's no `unistd.h` file in the root of the `include` directory but instead there are several ones at `include/asm` & `include/asm-generic`, and don't know what it could get... :-/

**Comment by piranna** [comment]
I forgot to say, I'm using the unstable release v0.11.14, I'm going to test to use the latest one v0.11.15 tomorrow.

**Comment by piranna** [comment]
I can confirm that it's still not working on v0.11.15.

**Comment by skeldoy** [comment]
I get the same thing when I try to compile v0.10.28 on FreeBSD ARM (raspberry pi).
