### ISSUE TITLE
compilation of node fail on Solaris 11.2 using gcc 4.8.2

### ISSUE THREAD

**Issue by cgalibern** [nodejs/node-v0.x-archive#9351]
During build on Solaris 11.2 node using gcc 4.8.2
with following configure command:
   ./configure --dest-cpu=x64  --dest-os=solaris --prefix=/opt/node 

gmake fails with following output:
g++ '-DV8_TARGET_ARCH_X64' '-D__C99FEATURES__=1' '-DENABLE_DISASSEMBLER' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DENABLE_HANDLE_ZAPPING' -I../deps/v8  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -fno-strict-aliasing -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /cgasolaris/home/cgaliber/apache/git/node/out/Release/.deps//cgasolaris/home/cgaliber/apache/git/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o.d.raw  -c -o /cgasolaris/home/cgaliber/apache/git/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o ../deps/v8/src/accessors.cc
In file included from ../deps/v8/src/objects-inl.h:17:0,
                 from ../deps/v8/src/v8.h:39,
                 from ../deps/v8/src/accessors.cc:5:
../deps/v8/src/conversions-inl.h: In function 'double v8::internal::DoubleToInteger(double)':
../deps/v8/src/conversions-inl.h:70:7: error: '**builtin_isnan' is not a member of 'std'
   if (std::isnan(x)) return 0;
       ^
../deps/v8/src/conversions-inl.h:70:7: note: suggested alternative:
<built-in>:0:0: note:   '__builtin_isnan'
In file included from /usr/include/math.h:13:0,
                 from /usr/gcc/4.8/include/c++/4.8.2/cmath:44,
                 from ../deps/v8/src/utils.h:11,
                 from ../deps/v8/src/assert-scope.h:10,
                 from ../deps/v8/src/v8.h:33,
                 from ../deps/v8/src/accessors.cc:5:
../deps/v8/src/conversions-inl.h:71:13: error: expected unqualified-id before '__extension**'
   if (!std::isfinite(x) || x == 0) return x;
             ^
../deps/v8/src/conversions-inl.h:71:13: error: expected ')' before '**extension**'
In file included from ../deps/v8/src/v8.h:39:0,
                 from ../deps/v8/src/accessors.cc:5:
../deps/v8/src/objects-inl.h: In member function 'bool v8::internal::Object::IsNaN() const':
../deps/v8/src/objects-inl.h:1090:34: error: '__builtin_isnan' is not a member of 'std'
   return this->IsHeapNumber() && std::isnan(HeapNumber::cast(this)->value());
                                  ^
../deps/v8/src/objects-inl.h:1090:34: note: suggested alternative:
<built-in>:0:0: note:   '__builtin_isnan'
../deps/v8/src/objects-inl.h: In member function 'void v8::internal::FixedDoubleArray::set(int, double)':
../deps/v8/src/objects-inl.h:2266:7: error: '__builtin_isnan' is not a member of 'std'
   if (std::isnan(value)) value = canonical_not_the_hole_nan_as_double();
       ^
../deps/v8/src/objects-inl.h:2266:7: note: suggested alternative:
<built-in>:0:0: note:   '__builtin_isnan'

**Comment by cgalibern** [comment]
it seems that it need '-D _GLIBCXX_USE_C99_MATH', 
I have tried it on https://github.com/cgalibern/node/commit/4b75bcdf809d786edf6c5efeca7f1fc3067d5cb8
