### ISSUE TITLE
Node does not build on FreeBSD 10.1 Release.

### ISSUE THREAD

**Issue by hbowden** [nodejs/node-v0.x-archive#25665]
I tried compiling Node with clang 3.6.1, but the build fails on...

```
../deps/v8/src/base/platform/platform-freebsd.cc: In static member function 'static std::vector<v8::base::OS::SharedLibraryAddress> v8::base::OS::GetSharedLibraryAddresses()':
../deps/v8/src/base/platform/platform-freebsd.cc:159:12: error: request for member 'push_back' in 'result', which is of non-class type 'int'
     result.push_back(SharedLibraryAddress(start_of_path, start, end));
            ^
gmake[1]: *** [/usr/home/nah/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-freebsd.o] Error 1
gmake[1]: *** Waiting for unfinished jobs....
../deps/v8/src/base/platform/platform-posix.cc: In static member function 'static int v8::base::OS::GetCurrentThreadId()':
../deps/v8/src/base/platform/platform-posix.cc:330:41: error: invalid static_cast from type 'pthread_t {aka pthread*}' to type 'int'
   return static_cast<int>(pthread_self());
```

clang also spotted some out of bounds access.

```
./deps/v8/src/hydrogen-check-elimination.cc: In member function 'void v8::internal::HFlowEngine<State, Effects>::AnalyzeDominatedBlocks(v8::internal::HBasicBlock*, State*) [with State = v8::internal::HCheckTable; Effects = v8::internal::HCheckMapsEffects]':
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
       HCheckTableEntry* entry = &entries_[i];
                                            ^
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
       HCheckTableEntry* entry = &entries_[i];
                                            ^
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
../deps/v8/src/hydrogen-check-elimination.cc:668:44: warning: array subscript is above array bounds [-Warray-bounds]
../deps/v8/src/jsregexp.cc: In member function 'virtual void v8::internal::TextNode::FillInBMInfo(int, int, v8::internal::BoyerMooreLookahead*, bool)':
../deps/v8/src/jsregexp.cc:5824:36: warning: array subscript is above array bounds [-Warray-bounds]
             bm->Set(offset, chars[j]);
                                    ^
../deps/v8/third_party/fdlibm/fdlibm.cc: In function 'int v8::fdlibm::__kernel_rem_pio2(double*, double*, int, int)':
../deps/v8/third_party/fdlibm/fdlibm.cc:150:23: warning: array subscript is above array bounds [-Warray-bounds]
       int32_t j = iq[i];
                       ^
../deps/v8/third_party/fdlibm/fdlibm.cc:154:15: warning: array subscript is above array bounds [-Warray-bounds]
           iq[i] = 0x1000000 - j;
               ^
../deps/v8/third_party/fdlibm/fdlibm.cc:157:13: warning: array subscript is above array bounds [-Warray-bounds]
         iq[i] = 0xffffff - j;
             ^

gmake[1]: *** [/usr/home/nah/node/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-posix.o] Error 1
../deps/v8/src/runtime.cc: In function 'v8::internal::Object* v8::internal::ConvertCaseHelper(v8::internal::Isolate*, v8::internal::String*, v8::internal::SeqString*, int, unibrow::Mapping<Converter, 128>*) [with Converter = unibrow::ToLowercase]':
../deps/v8/src/runtime.cc:6409:29: warning: array subscript is above array bounds [-Warray-bounds]
         result->Set(i, chars[j]);
                             ^
../deps/v8/src/runtime.cc: In function 'v8::internal::Object* v8::internal::ConvertCaseHelper(v8::internal::Isolate*, v8::internal::String*, v8::internal::SeqString*, int, unibrow::Mapping<Converter, 128>*) [with Converter = unibrow::ToUppercase]':
../deps/v8/src/runtime.cc:6409:29: warning: array subscript is above array bounds [-Warray-bounds]
gmake: *** [node] Error 2
```

**Comment by dnakamura** [comment]
That would be an issue with V8, looks like it was fixed in 3.29.52 specifically, v8/v8-git-mirror@72e27a3  and v8/v8-git-mirror@e8b9f2d until node updates its v8 you can apply those changes

**Comment by 2trill2spill** [comment]
Why not just apply those changes to Node's V8 or is Node's V8 being updated soon? Either way thanks for the reply.

**Comment by dnakamura** [comment]
Updating v8 is out of the question for now, however if you can confirm that the changes resolve the issue I can put in a pull request to update the relevant files
